/**
 * TMDB values come from the root ".env". Metro loads them via shims/@env
 * (generated by scripts/write-env-shim.js — see .env.example). Do not commit ".env".
 */
import {TMDB_API_KEY as envKey} from '@env';

export const TMDB_API_KEY = (envKey || '').trim();

export const TMDB_IMAGE_BASE = 'https://image.tmdb.org/t/p';
